---
root: true
env:
  browser: true
  es6: true
  jquery: true
extends:
- eslint:recommended
globals:
  enquire: writable
  Colcade: writable
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jsx: true
    modules: true
rules:
  camelCase: 0
  comma-dangle:
  - error
  - never
  no-empty: 0
  indent:
  - error
  - tab
  no-unused-vars: 0
  linebreak-style:
  - error
  - unix
  # quotes:
  # - error
  # - double
  semi: 0
  # semi: 0
  # - error
  # - always
