[build]
  publish = "dist"
  command = "pnpm build"

[[plugins]]

	# Opt-in to the Netlify Lighthouse plugin (choose one):

	# 1. Go to your site on https://app.netlify.com and navigate to the Integrations tab, search for the `Lighthouse` plugin
	# 2. Or via `npm install -D @netlify/plugin-lighthouse`

	# Read more: https://github.com/netlify/netlify-plugin-lighthouse

	package = "@netlify/plugin-lighthouse"

	# optional, fails build when a category is below a threshold
	[plugins.inputs.thresholds]
		performance = 1.0
		accessibility = 1.0
		best-practices = 1.0
		seo = 1.0

	[plugins.inputs]
		output_path = "reports/lighthouse/index.html"

# REDIRECT and HEADERS examples

# Redirect rule example
# For more information see:- https://www.netlify.com/docs/netlify-toml-reference/

#[[redirects]]
#  from = "/*"
#  to = "/blog/:splat"
# status = 302

# The default HTTP status code is 301, but you can define a different one e.g.

# Headers rule example
# For more information see:- https://www.netlify.com/docs/netlify-toml-reference/

#[[headers]]
#   Define which paths this specific [[headers]] block will cover.
#   for = "/*"

#[headers.values]
#   X-Frame-Options = "DENY"
#   X-XSS-Protection = "1; mode=block"
#   Content-Security-Policy = "frame-ancestors https://www.facebook.com"

# Redirects and headers are GLOBAL for all builds – they do not get scoped to
# contexts no matter where you define them in the file.
# For context-specific rules, use _headers or _redirects files, which are
# applied on a PER-DEPLOY basis.
